[package]
name = "muloom"
version = "0.1.0"
edition = "2021"

[dependencies]
tauri = { version = "2.0.0", features = ["default"] }

[build-dependencies]
tauri-build = { version = "2.0.0", features = [] }
